---
title: '2019-03-20'
author: "廖翊彣"
date: "3/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
dialogue <- c('小明說："明天不用上課。"',
               '小花說："真的嗎？"')

cat(dialogue, sep="\n")
```

#logical T=1 F=0
```{r}
aLogical <- c(T,TRUE,F,FALSE,FALSE)
class(aLogical)
```

```{r}
sum(aLogical)
```

#factor

```{r}
studentMajors <- factor(
  c("經濟系", "經濟系", "法律系")
)
studentMajors
studentMajor <- c("經濟系", "經濟系", "法律系")
studentMajor
```

```{r}
class(studentMajors)
```
```{r}
class(studentMajor)
```


```{r}
typeof(studentMajors)
```

```{r}
typeof(studentMajor)
```

```{r}
levels(studentMajors)
```
```{r}
as.integer(studentMajors)
```
```{r}
stringInteger <- c("1","2","-11")
class(stringInteger) # 無法進行數值運算

trueInteger <- as.integer(stringInteger)
class(trueInteger) # 可以進行數值運算
```

```{r}
birthplace <- factor(
  c("台北市","台北市","台中市","台中市","台中市")
  )
class(birthplace)
typeof(birthplace)
levels(birthplace)
as.integer(birthplace)
```

```{r}
class(birthplace)
typeof(birthplace)
levels(birthplace)
as.integer(birthplace)
```
#date and time
```{r}
library(lubridate)
```
```{r}
dtObject<-ymd_hms("1970-01-01 00:02:53") 
dtObjectVector<-ymd_hms(
  c("1970-01-01 00:02:53",
    "1980-02-11 11:25:22")
)
```

```{r}
class(dtObject)
```
```{r}
dtObject
```
```{r}
typeof(dtObject)
```
```{r}
as.double(dtObject)
as.integer(dtObject)
```


